# Generated by Django 3.1.3 on 2022-04-05 03:02

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.CharField(max_length=9, null=True, verbose_name='ZipCode')),
                ('houseNumber', models.CharField(max_length=6, null=True, verbose_name='Number')),
                ('nghood', models.CharField(max_length=50, null=True, verbose_name='Neighborhood')),
                ('city', models.CharField(max_length=40, null=True, verbose_name='City/Town')),
                ('houseType', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('state', models.CharField(max_length=2, null=True, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail (Obrigatório para acesso ao sistema)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='administrador')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.address', unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=(models.Model, api.models.GetAddressesMixin),
        ),
    ]
