# Generated by Django 3.1.3 on 2022-04-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220405_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehistory',
            old_name='user_upd',
            new_name='user_add',
        ),
    ]
